#!/bin/bash

##.1
cfdisk /dev/nvme0n1 &&
  mkfs.vfat -F 32 /dev/nvme0n1p1 &&
  cryptsetup luksFormat --key-size 512 /dev/nvme0n1p2 &&
  cryptsetup luksOpen /dev/nvme0n1p2 root &&
  mkfs.btrfs -L rootfs /dev/mapper/root &&
  rm -R /mnt/gentoo &&
  mkdir /mnt/gentoo &&
  mount /dev/mapper/root /mnt/gentoo

btrfs su cr /mnt/gentoo/@ &&
  btrfs su cr /mnt/gentoo/@home &&
  btrfs su cr /mnt/gentoo/@opt &&
  btrfs su cr /mnt/gentoo/@root &&
  btrfs su cr /mnt/gentoo/@srv &&
  btrfs su cr /mnt/gentoo/@nix &&
  btrfs su cr /mnt/gentoo/@usr@local &&
  btrfs su cr /mnt/gentoo/@var && 
  btrfs su cr /mnt/gentoo/@var@cache && 
  btrfs su cr /mnt/gentoo/@var@crash &&
  btrfs su cr /mnt/gentoo/@var@tmp &&
  btrfs su cr /mnt/gentoo/@var@spool &&
  btrfs su cr /mnt/gentoo/@var@log && 
  btrfs su cr /mnt/gentoo/@var@log@audit &&
  btrfs su cr /mnt/gentoo/@snapshots && 
  umount /mnt/gentoo 


mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@ /dev/mapper/root /mnt/gentoo &&
  mkdir /mnt/gentoo/home &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@home /dev/mapper/root /mnt/gentoo/home &&
  mkdir /mnt/gentoo/opt &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@opt /dev/mapper/root /mnt/gentoo/opt && 
  mkdir /mnt/gentoo/root &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@root /dev/mapper/root /mnt/gentoo/root &&
  mkdir /mnt/gentoo/srv &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@srv /dev/mapper/root /mnt/gentoo/srv &&
  mkdir /mnt/gentoo/nix &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@nix /dev/mapper/root /mnt/gentoo/nix &&
  mkdir -p /mnt/gentoo/usr/local &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@usr@local /dev/mapper/root /mnt/gentoo/usr/local &&    
  mkdir /mnt/gentoo/var && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var /dev/mapper/root /mnt/gentoo/var &&
  mkdir /mnt/gentoo/var/cache && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@cache /dev/mapper/root /mnt/gentoo/var/cache &&
  mkdir /mnt/gentoo/var/crash && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@crash /dev/mapper/root /mnt/gentoo/var/crash &&
  mkdir /mnt/gentoo/var/tmp  && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@tmp /dev/mapper/root /mnt/gentoo/var/tmp &&
  mkdir /mnt/gentoo/var/spool  && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@spool /dev/mapper/root /mnt/gentoo/var/spool &&
  mkdir /mnt/gentoo/var/log && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@log /dev/mapper/root /mnt/gentoo/var/log && 
  mkdir /mnt/gentoo/var/log/audit && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@log@audit /dev/mapper/root /mnt/gentoo/var/log/audit && 
  mkdir /mnt/gentoo/.snapshots && 
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@snapshots /dev/mapper/root /mnt/gentoo/.snapshots  
  

cd /mnt/gentoo && wget https://distfiles.gentoo.org/releases/amd64/autobuilds/20241110T170333Z/stage3-amd64-hardened-openrc-20241110T170333Z.tar.xz && tar xpvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner &&
  rm -R /mnt/gentoo/etc/portage/make.conf &&
  cp -R /home/ahsan/.dots/gentoo/etc/portage/make.conf /mnt/gentoo/etc/portage/ && 
  rm -R /mnt/gentoo/etc/portage/package.accept_keywords && 
  cp -R /home/ahsan/.dots/gentoo/etc/portage/package.accept_keywords /mnt/gentoo/etc/portage/ && 
  cp -R /home/ahsan/.dots/gentoo/etc/portage/profile/use.mask /mnt/gentoo/etc/portage/profile/ && 
  cp -R /home/ahsan/.dots/gentoo/etc/portage/profile/package.provided /mnt/gentoo/etc/portage/profile/ && 
  rm -R /mnt/gentoo/etc/portage/package.use && 
  cp -R /home/ahsan/.dots/gentoo/etc/portage/package.use /mnt/gentoo/etc/portage/ && 
  rm -R /mnt/gentoo/etc/portage/package.mask && 
  cp -R /home/ahsan/.dots/gentoo/etc/portage/package.mask /mnt/gentoo/etc/portage/ && 
  mkdir --parents /mnt/gentoo/etc/portage/repos.conf && cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf && cp --dereference /etc/resolv.conf /mnt/gentoo/etc/ && mount --types proc /proc /mnt/gentoo/proc && mount --rbind /sys /mnt/gentoo/sys && mount --make-rslave /mnt/gentoo/sys && mount --rbind /dev /mnt/gentoo/dev && mount --make-rslave /mnt/gentoo/dev && mount --bind /run /mnt/gentoo/run && mount --make-slave /mnt/gentoo/run && test -L /dev/shm && rm /dev/shm && mkdir /dev/shm && mount -t tmpfs -o nosuid,nodev,noexec shm /dev/shm && chmod 1777 /dev/shm

##.5
chroot /mnt/gentoo /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"

##.6
emerge-webrsync && emerge --sync --quiet
eselect profile set 42

ln -sf ../usr/share/zoneinfo/Asia/Dhaka /etc/localtime && nano /etc/locale.gen && locale-gen && eselect locale list && eselect locale set 4 && env-update && source /etc/profile && export PS1="(chroot) ${PS1}" 

linux-headers ->  glibc -> binutils -> gcc -> glibc -> binutils -> rust -> python -> go -> gcc -> nodejs

emerge linux-headers && emerge glibc && emerge binutils && emerge python && emerge gcc && eselect gcc list && eselect gcc set 2  && env-update && source /etc/profile && export PS1="(chroot) ${PS1}" && emerge dev-build/libtool

emerge glibc && emerge binutils && emerge python && emerge gcc

emerge sys-devel/clang sys-devel/llvm sys-libs/compiler-rt sys-libs/llvm-libunwind sys-devel/lld sys-libs/compiler-rt-sanitizers  && source /etc/profile && export PS1="(chroot) ${PS1}"

emerge automake && emerge -ev @world --exclude gcc

emerge -aq app-eselect/eselect-repository dev-vcs/git && eselect repository remove gentoo && eselect repository add gentoo git https://github.com/gentoo-mirror/gentoo.git  && emaint sync -r gentoo && eselect repository enable guru pentoo edgets && emerge --sync

systemd-machine-id-setup && hostnamectl set-hostname zephyrus && emerge app-admin/sudo && passwd && useradd -m -G users,wheel,audio,video -s /bin/bash ahsan && passwd ahsan && EDITOR=nvim visudo  

##.9
* kernel setup
emerge sys-kernel/cachyos-sources sys-kernel/linux-firmware sys-kernel/linux-headers sys-apps/fwupd sys-fs/cryptsetup sys-firmware/sof-firmware sys-fs/genfstab sys-kernel/installkernel sys-kernel/modprobed-db sys-fs/btrfs-progs sys-apps/rng-tools net-misc/networkmanager && eselect kernel set 1 && ls -l /usr/src/linux

##.10
mount /dev/nvme0n1p1 /boot
genfstab -U / >> /etc/fstab

tmpfs  /tmp  tmpfs  defaults,noexec,nosuid,rootcontext=system_u:object_r:tmp_t  0 0
tmpfs  /run   tmpfs  mode=0755,nosuid,nodev,rootcontext=system_u:object_r:var_run_t  0 0

** gentoo config examples
1. main handbook (done) 
2. dracut (done)
3. systemd (done)
4. zram (done)
5. printing
6. systemd-boot
7. zstd (done)
8. bluetooth (done)
9. dm-crypt (done)
10. amd microcode (done)
11. input devices -> include asus g14
12. cups (done)
13. droidcam (done)
14. nvidia
15. sound
16. openrgb


lsblk -o name,uuid

sda                                           
|-sda1                                        031E-C045
`-sda2                                        be21e075-9797-43a1-8b51-856a11bc03a5
  `-luks-be21e075-9797-43a1-8b51-856a11bc03a5 c0c56099-3375-47dd-872a-57334599abe3


nvme0n1                                       
|-nvme0n1p1                                   BB7E-0018
`-nvme0n1p2                                   8a848dda-43e9-4ca0-a44c-87e69fa5fc9e
  `-root                                      19572889-b1b2-4efe-ae75-274a1bc67667

# dracut setup
nvim /etc/dracut.conf
hostonly="yes"
compress="zstd"
add_dracutmodules+=" crypt dm rootfs-block "
omit_dracutmodules+=" network cifs nfs nbd brltty "
force_drivers+=" btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm "
kernel_cmdline+=" root=UUID=19572889-b1b2-4efe-ae75-274a1bc67667 rd.luks.uuid=8a848dda-43e9-4ca0-a44c-87e69fa5fc9e "

efibootmgr --create --disk /dev/nvme0n1 --label "Gentoo" --loader "vmlinuz-6.1.28-gentoo" --unicode "initrd=initramfs-6.1.28-gentoo rd.luks.uuid=8a848dda-43e9-4ca0-a44c-87e69fa5fc9e"

### Applyiing patches 
* apply base-alll patch First
* test 

make nconfig KCFLAGS="-O2 -march=native -pipe -flto" 
make -j14 LLVM=1 KCFLAGS="-O2 -march=native -pipe -flto" 
emerge x11-drivers/nvidia-drivers gui-libs/egl-wayland gui-libs/egl-gbm gui-libs/egl-x11 media-libs/nvidia-vaapi-driver sys-firmware/nvidia-firmware sys-process/nvtop x11-drivers/xf86-video-amdgpu  
make modules_install -j14 LLVM=1 KCFLAGS="-O2 -march=native -pipe -flto" 
make install -j14 LLVM=1 KCFLAGS="-O2 -march=native -pipe -flto"

make nconfig LLVM=1 KCFLAGS="-O3 -march=native -pipe -flto=thin" 
make -j14 LLVM=1 KCFLAGS="-O3 -march=native -pipe -flto=thin"   
make modules_install -j14 LLVM=1 KCFLAGS="-O3 -march=native -pipe -flto=thin"
emerge x11-drivers/nvidia-drivers gui-libs/egl-wayland gui-libs/egl-gbm gui-libs/egl-x11 media-libs/nvidia-vaapi-driver sys-process/nvtop x11-drivers/xf86-video-amdgpu
make install -j14 LLVM=1 KCFLAGS="-O3 -march=native -pipe -flto=thin" 

##.12a Systemd-boot Setup
bootclt install
nvim /boot/loader/loader.conf
default b1600d8c2083b7b59a984e1a673d4739*
timeout 5
console-mode auto

nvim /boot/loader/entries/b1600d8c2083b7b59a984e1a673d4739-6.6.62-cachyos-6.6.62.conf (autogenerated)
# Boot Loader Specification type#1 entry
# File created by /usr/lib/kernel/install.d/90-loaderentry.install (systemd 256.7)
title      Gentoo Linux
version    6.6.62-cachyos-6.6.62
machine-id b1600d8c2083b7b59a984e1a673d4739
sort-key   gentoo
options    nvme_load=YES nowatchdog rw rootflags=subvol=/@ rd.luks.uuid=be21e075-9797-43a1-8b51-856a11bc03a5 root=/dev/mapper/luks-be21e075-9797-43a1-8b51-856a11bc03a5 nvidia_drm.modeset=1 systemd.machine_id=8b0213fba2c14dc9a50d3ee41931eea0
linux      /b1600d8c2083b7b59a984e1a673d4739/6.6.62-cachyos-6.6.62/linux
initrd     /b1600d8c2083b7b59a984e1a673d4739/6.6.62-cachyos-6.6.62/initrd


##.12b grub setup
# nvim /etc/default/grub
# 12b.1 maximum options
GRUB_CMDLINE_LINUX_DEFAULT="nvme_load=YES nowatchdog rw rootflags=subvol=/@ rd.luks.uuid=be21e075-9797-43a1-8b51-856a11bc03a5 root=/dev/mapper/luks-be21e075-9797-43a1-8b51-856a11bc03a5 nvidia_drm.modeset=1 systemd.machine_id=8b0213fba2c14dc9a50d3ee41931eea0 rootfstype=btrfs" 
GRUB_CMDLINE_LINUX="quiet loglevel=0 init=/lib/systemd/systemd rd.luks.options=discard root_trim=yes"

# 12b.2 minimal options (default)
GRUB_CMDLINE_LINUX_DEFAULT="nvme_load=YES nowatchdog rw rootflags=subvol=/@ rd.luks.uuid=be21e075-9797-43a1-8b51-856a11bc03a5 root=/dev/mapper/luks-be21e075-9797-43a1-8b51-856a11bc03a5 nvidia_drm.modeset=1 rootfstype=btrfs" 
GRUB_CMDLINE_LINUX="quiet loglevel=0 init=/lib/systemd/systemd"



grub-install --target=x86_64-efi --efi-directory=/boot && grub-install --target=x86_64-efi --efi-directory=/boot --removable && grub-mkconfig -o /boot/grub/grub.cfg

##.13

# System
emerge sys-apps/mlocate app-portage/smart-live-rebuild app-portage/gentoolkit sys-apps/grep app-arch/unzip app-arch/zip app-arch/unrar sys-fs/btrfs-progs sys-fs/dosfstools net-misc/wget net-misc/curl sys-apps/ripgrep sys-apps/fd sys-power/upower net-misc/networkmanager sys-apps/zram-generator media-video/wireplumber sys-process/btop sys-apps/file media-video/ffmpegthumbnailer app-arch/7zip media-gfx/imagemagick \
  sys-apps/bat app-shells/zoxide app-shells/fzf app-shells/fzf-tab app-shells/zsh app-shells/zsh-completions app-shells/zsh-syntax-highlighting app-shells/zsh-autosuggestions app-shells/zsh-history-substring-search app-shells/gentoo-zsh-completions app-shells/gitstatus app-shells/powerlevel10k app-shells/ohmyzsh sys-apps/eza app-misc/zellij app-misc/yazi gui-apps/foot gui-apps/foot-terminfo \
  media-fonts/jetbrains-mono media-fonts/ubuntu-font-family media-fonts/nerdfonts \
  gui-libs/hyprutils dev-libs/hyprlang gui-libs/hyprcursor dev-util/hyprwayland-scanner gui-apps/hyprpaper gui-apps/hyprpicker gui-apps/hypridle gui-apps/hyprlock gui-libs/aquamarine gui-libs/xdg-desktop-portal-hyprland gui-wm/hyprland gui-wm/hyprland-contrib dev-libs/hyprland-protocols gui-apps/hyprsunset gui-apps/nwg-drawer gui-apps/nwg-menu app-misc/nwg-look gui-libs/greetd gui-apps/nwg-hello gui-apps/anyrun gui-apps/rofi-wayland gui-apps/qt6ct x11-misc/qt5ct x11-themes/kvantum x11-libs/libnotify gui-apps/grim gui-apps/slurp gui-apps/wf-recorder x11-base/xwayland dev-libs/gjs dev-lang/sassc app-misc/brightnessctl media-sound/pavucontrol gui-apps/swappy gui-apps/swww net-wireless/gnome-bluetooth  \
  app-forensics/aide sys-apps/haveged app-forensics/lynis sys-process/audit app-admin/sysstat sys-process/acct net-analyzer/nmap net-analyzer/wireshark app-crypt/johntheripper net-wireless/aircrack-ng www-apps/beef sys-apps/apparmor sys-apps/apparmor-utils sec-policy/apparmor-profiles sys-libs/libapparmor \
  app-containers/docker app-containers/docker-cli app-containers/docker-compose app-containers/docker-credential-helpers app-containers/distrobox app-containers/lxd app-containers/lxc \
  gnome-base/gvfs xfce-base/thunar xfce-base/thunar-volman xfce-extra/thunar-archive-plugin xfce-extra/thunar-media-tags-plugin xfce-base/tumbler \
  app-editors/emacs app-editors/neovim app-editors/vscodium dev-vcs/lazygit dev-python/python-pam dev-python/pynvim app-editors/emacs-lsp-booster dev-tex/texlab media-gfx/maim dev-python/pipx dev-python/yapf dev-python/black dev-python/isort dev-python/matplotlib dev-python/scipy sci-biology/biopython dev-python/pandas gui-apps/wl-clipboard dev-lang/typescript dev-python/pipx dev-python/pip dev-vcs/git dev-vcs/git-lfs dev-util/git-delta nodejs \
  net-im/zoom net-im/discord app-text/xournalpp app-text/zathura app-text/zathura-meta sci-chemistry/pymol app-text/zotero-bin app-admin/bitwarden-desktop-bin app-office/notesnook-bin app-office/onlyoffice-bin net-irc/halloy net-misc/dropbox app-office/obsidian www-client/zen-browser media-video/mpv media-sound/spotify www-client/google-chrome www-apps/element app-office/standartnotes-bin \
  app-backup/snapper app-backup/snapper-gui app-backup/btrfs-assistant app-backup/grub-btrfs 


##.B
systemctl preset-all && systemctl enable NetworkManager sysstat auditd rngd nvidia-suspend.service nvidia-resume.service systemd-timesyncd


##.C setup snapper
sudo umount /.snapshots/ && sudo rm -r /.snapshots/ && sudo snapper -c root create-config / && sudo btrfs subvolume delete /.snapshots && sudo mkdir /.snapshots && sudo mount -a && sudo chmod 750 /.snapshots && sudo lvim /etc/snapper/configs/root && sudo systemctl enable --now snapper-timeline.timer && sudo systemctl enable --now snapper-cleanup.timer 

##.D Sysctl
sudo nvim /etc/sysctl.d/harden.conf
kernel.kptr_restrict=2
kernel.dmesg_restrict=1
kernel.printk=3 3 3 3
kernel.unprivileged_bpf_disabled=1
net.core.bpf_jit_harden=2
dev.tty.ldisc_autoload=0
vm.unprivileged_userfaultfd=0
kernel.kexec_load_disabled=1
kernel.sysrq=4
kernel.unprivileged_userns_clone=0
kernel.perf_event_paranoid=3
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_rfc1337=1
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv6.conf.all.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.icmp_echo_ignore_all=1
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0
net.ipv6.conf.all.accept_source_route=0
net.ipv6.conf.default.accept_source_route=0
net.ipv6.conf.all.accept_ra=0
net.ipv6.conf.default.accept_ra=0
net.ipv4.tcp_sack=0
net.ipv4.tcp_dsack=0
net.ipv4.tcp_fack=0
kernel.yama.ptrace_scope=2
vm.mmap_rnd_bits=32
vm.mmap_rnd_compat_bits=16
fs.protected_symlinks=1
fs.protected_hardlinks=1
fs.protected_fifos=2
fs.protected_regular=2

##.D Issue
-- WARNING -- This system is for the use of authorized users only. Individuals 
using this computer system without authority or in excess of their authority 
are subject to having all their activities on this system monitored and 
recorded by system personnel. Anyone using this system expressly consents to 
such monitoring and is advised that if such monitoring reveals possible 
evidence of criminal activity system personal may provide the evidence of such 
monitoring to law enforcement officials.

##.E Post-install chroot
cryptsetup luksOpen /dev/nvme0n1p2 root  && 
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@ /dev/mapper/root /mnt/gentoo &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@home /dev/mapper/root /mnt/gentoo/home &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@opt /dev/mapper/root /mnt/gentoo/opt && 
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@root /dev/mapper/root /mnt/gentoo/root &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@srv /dev/mapper/root /mnt/gentoo/srv &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@nix /dev/mapper/root /mnt/gentoo/nix &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@usr@local /dev/mapper/root /mnt/gentoo/usr/local &&    
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var /dev/mapper/root /mnt/gentoo/var &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var@cache /dev/mapper/root /mnt/gentoo/var/cache &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var@crash /dev/mapper/root /mnt/gentoo/var/crash &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var@log /dev/mapper/root /mnt/gentoo/var/log && 
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var@log@audit /dev/mapper/root /mnt/gentoo/var/log/audit && 
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var@tmp /dev/mapper/root /mnt/gentoo/var/tmp &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@spool /dev/mapper/root /mnt/gentoo/var/spool &&
  mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@snapshots /dev/mapper/root /mnt/gentoo/.snapshots && 
  mkdir --parents /mnt/gentoo/etc/portage/repos.conf && 
  cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf &&
  cp --dereference /etc/resolv.conf /mnt/gentoo/etc/ && 
  mount --types proc /proc /mnt/gentoo/proc && 
  mount --rbind /sys /mnt/gentoo/sys && mount --make-rslave /mnt/gentoo/sys && 
  mount --rbind /dev /mnt/gentoo/dev && mount --make-rslave /mnt/gentoo/dev && 
  mount --bind /run /mnt/gentoo/run && mount --make-slave /mnt/gentoo/run && 
  test -L /dev/shm &&
  rm /dev/shm && mkdir /dev/shm && 
  mount -t tmpfs -o nosuid,nodev,noexec shm /dev/shm && chmod 1777 /dev/shm

## Misc
nvim /etc/modprobe.d/nvidia.conf
options nvidia-drm modeset=1 
options nvidia NVreg_UsePageAttributeTable=1


nvim /etc/modprobe.d/nvidia-power-management.conf
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/tmp

#scaling apps
--force-device-scale-factor=1.75 %U

grep 'app-emacs/' /var/lib/portage/world | xargs --open-tty emerge --ask --deselect; emerge --ask --depcleaneselect repository add brave-overlay git https://gitlab.com/jason.oliveira/brave-overlay.git

git config --global credential.helper /usr/bin/git-credential-libsecret


sudo chage --mindays 40 \
--maxdays 120 --warndays 30 ahsan

# chrome sandbox
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox

sudo lvim /usr/share/gvfs/mounts/network.mount
AutoMount=false

 *   CONFIG_NF_CT_NETLINK_HELPER:	 is not set when it should be.
 *   CONFIG_NFT_OBJREF:	 is not set when it should be.

 *   CONFIG_PPP_DEFLATE:         missing Deflate compression (optional, but highly recommended)
 *   CONFIG_PPP_BSDCOMP:         missing BSD-Compress compression (optional, but highly recommended)

CONFIG_NF_CT_NETLINK_HELPER

# Install nvhpc
wget https://developer.download.nvidia.com/hpc-sdk/23.9/nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
tar xpzf nvhpc_2023_239_Linux_x86_64_cuda_12.2.tar.gz
nvhpc_2023_239_Linux_x86_64_cuda_12.2/install

# Tinker9 installation
git clone --recurse-submodules https://github.com/TinkerTools/tinker9.git
cd tinker9 && mkdir build && cd build
cmake -DCMAKE_Fortran_COMPILER=gfortran -DCOMPUTE_CAPABILITY=70 ..
make -j22
make test

rustup-init-gentoo

** SECURITY **
/etc/security/limits.conf
*    soft core 0
*    hard core 0
*    hard nproc 15
*    hard rss 10000
*    -    maxlogins 2
@dev hard core 100000
@dev soft nproc 20
@dev hard nproc 35
@dev -    maxlogins 10

chroot /mnt/gentoo /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"

mount /dev/nvme0n1p1 /boot
