#!/bin/bash
hyprpm update
hyprpm add https://github.com/hyprwm/hyprland-plugins
hyprpm add https://github.com/outfoxxed/hy3
hyprpm add https://github.com/KZDKM/Hyprspace
hyprpm enable hyprexpo
hyprpm enable hy3
hyprpm enable Hyprspace
