#!/bin/bash
echo "Installing Emacs"
sudo apt install -y libgccjit-14-dev libmagick++-dev libtree-sitter-dev libgnutls28-dev libxaw7-dev
cd && wget https://gnu.mirror.constant.com/emacs/emacs-29.4.tar.xz
tar -xvf emacs-29.4.tar.xz && cd emacs-29.4 && ./autogen.sh
./configure --with-pgtk --with-native-compilation --with-mailutils --with-tree-sitter --with-threads 
make -j16 
sudo make install && cd 
sudo rm -rf emacs*
