#!/bin/bash
echo "Installing hyprwayland-scanner"
sudo apt install -y libpugixml-dev
cd && git clone https://github.com/hyprwm/hyprwayland-scanner
cd hyprwayland-scanner
cmake -B build
cmake --build build -j5
sudo cmake --install build
cd build/
sudo install -Dm755 hyprwayland-scanner "/usr/local/bin/hyprwayland-scanner"
cd && sudo rm -rf hyprwayland-scanner
