#!/bin/bash
echo "Installing Hyprutils"
sudo apt install -y libpixman-1-dev
cd && git clone https://github.com/hyprwm/hyprutils.git
cd hyprutils
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target all -j$(nproc 2>/dev/null || getconf _NPROCESSORS_CONF)
sudo cmake --install build
cd && sudo rm -rf hyprutils
