#!/bin/bash
echo "Installing nwg-drawer"
sleep 2
cd && git clone https://github.com/nwg-piotr/nwg-drawer.git
cd nwg-drawer && git checkout v0.6.0
make get
make build
sudo make install
cd && sudo rm -R nwg-drawer
