#!/bin/zsh
alias aac="sudo apt autoclean"
alias abd="sudo apt build-dep"
alias ac="sudo apt clean"
alias ad="sudo apt update"
alias adg="sudo apt update && sudo apt upgrade"
alias adu="sudo apt update && sudo apt dist-upgrade"
alias afu="sudo apt-file update"
alias au="sudo apt upgrade"
alias ai="sudo apt install"
