#!/bin/bash
sudo dnf install make cmake xxd fuse-devel glib2-devel cairo-devel librsvg2-devel libarchive-devel libXpm-devel rust-curl+openssl-sys-devel boost-devel qt5-qtbase-devel qt5-qtdeclarative-devel qt5-qttools-devel patchelf glibc-devel

cd && git clone https://github.com/TheAssassin/AppImageLauncher.git -b stable
cd AppImageLauncher
git submodule update --init --recursive
export PREFIX="/usr/local/"
mkdir build
cd build

cmake .. -DCMAKE_INSTALL_PREFIX="$PREFIX" -DUSE_SYSTEM_BOOST=true

# See https://github.com/TheAssassin/AppImageLauncher/issues/251 for more details why this is required
make libappimage libappimageupdate libappimageupdate-qt
cmake .

make
sudo make install
cd && sudo rm -rf AppImageLauncher
