#!/bin/sh

cfdisk /dev/nvme0n1 && mkfs.vfat -F 32 /dev/nvme0n1p1 &&
  cryptsetup --cipher aes-xts-plain64 --hash sha512 --use-random --verify-passphrase luksFormat /dev/nvme0n1p2 &&
  cryptsetup open --perf-no_read_workqueue --perf-no_write_workqueue --persistent /dev/nvme0n1p2 cryptroot &&
  mkfs.btrfs -f /dev/mapper/cryptroot && mount /dev/mapper/cryptroot /mnt

btrfs su cr /mnt/@ &&
  btrfs su cr /mnt/@home &&
  btrfs su cr /mnt/@opt &&
  btrfs su cr /mnt/@root &&
  btrfs su cr /mnt/@srv &&
  btrfs su cr /mnt/@usr@local &&
  btrfs su cr /mnt/@var &&
  btrfs su cr /mnt/@var@cache &&
  btrfs su cr /mnt/@pkg &&
  btrfs su cr /mnt/@var@crash &&
  btrfs su cr /mnt/@var@log &&
  btrfs su cr /mnt/@var@log@audit &&
  btrfs su cr /mnt/@var@tmp &&
  btrfs su cr /mnt/@snapshots &&
  umount /mnt

mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@ /dev/mapper/cryptroot /mnt &&
  mkdir /mnt/home &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@home /dev/mapper/cryptroot /mnt/home &&
  mkdir /mnt/opt &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@opt /dev/mapper/cryptroot /mnt/opt &&
  mkdir /mnt/root &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@root /dev/mapper/cryptroot /mnt/root &&
  mkdir /mnt/srv &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@srv /dev/mapper/cryptroot /mnt/srv &&
  mkdir -p /mnt/usr/local &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@usr@local /dev/mapper/cryptroot /mnt/usr/local &&
  mkdir /mnt/var &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var /dev/mapper/cryptroot /mnt/var &&
  mkdir /mnt/var/cache &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@cache /dev/mapper/cryptroot /mnt/var/cache &&
  mkdir -p /mnt/var/cache/pacman/pkg &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@pkg /dev/mapper/cryptroot /mnt/var/cache/pacman/pkg &&
  mkdir /mnt/var/crash &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@crash /dev/mapper/cryptroot /mnt/var/crash &&
  mkdir /mnt/var/log &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@log /dev/mapper/cryptroot /mnt/var/log &&
  mkdir /mnt/var/log/audit &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@log@audit /dev/mapper/cryptroot /mnt/var/log/audit &&
  mkdir /mnt/var/tmp &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@var@tmp /dev/mapper/cryptroot /mnt/var/tmp &&
  mkdir /mnt/.snapshots &&
  mount -o noatime,compress=zstd:3,space_cache=v2,discard=async,subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots &&
  mkdir /mnt/boot &&
  mount /dev/nvme0n1p1 /mnt/boot

pacstrap /mnt base base-devel devtools git neovim arch-install-scripts reflector dracut yay

genfstab -U /mnt >>/mnt/etc/fstab
arch-chroot /mnt

passwd && useradd -m -G users,wheel,audio,video -s /bin/bash ahsan && passwd ahsan && EDITOR=nvim visudo

## reflector setup
nvim /etc/xdg/reflector/reflector.conf
--save /etc/pacman.d/mirrorlist
--protocol https
--latest 25
--sort rate

reflector -l 25 --sort rate --save /etc/pacman.d/mirrorlist

## add endeavoros repos

ln -sf /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && hwclock --systohc && nvim /etc/locale.gen && locale-gen && echo "LANG=en_US.UTF-8" >>/etc/locale.conf

pacman -S unzip zip unrar btrfs-progs chrony dosfstools thunar thunar-volman thunar-media-tags-plugin thunar-archive-plugin tumbler zathura zathura-pdf-poppler papirus-icon-theme wget curl ripgrep fd python-pip zsh zsh-completions neofetch xdg-user-dirs python-pynvim mesa rng-tools haveged upower greetd lazygit lynis audit sysstat networkmanager acpid fzf flatpak fdupes ranger wl-clipboard kitty grim slurp wf-recorder vulkan-tools vulkan-headers vulkan-validation-layers hyprland nodejs npm rustup transmission-gtk cmake boost polkit-gnome tldr emacs-wayland nvidia-open-dkms

pacman -S linux-zen linux-zen-headers amd-ucode linux-firmware kernel-install-for-dracut nvidia-open-dkms nvidia-utils

# dracut setup
nvim /etc/dracut.conf
compress="zstd"
hostonly="yes"
dracutmodules+=" kernel-modules rootfs-block udev-rules usrmount base fs-lib shutdown "
add_dracutmodules+=" crypt dm rootfs-block "
omit_dracutmodules+=" network cifs nfs nbd brltty "
force_drivers+=" btrfs nvidia nvidia_modeset nvidia_uvm nvidia_drm "
kernel_cmdline="quiet loglevel=3 cryptdevice=UUID=a0117c0e-c7e3-4576-b550-164cc6292ab8:cryptroot root=/dev/mapper/cryptroot nvidia-drm.modeset=1 rootfstype=btrfs rootflags=rw root_trim=yes"
install_items+=" /etc/crypttab "

nvim /etc/crypttab
cryptroot UUID=a0117c0e-c7e3-4576-b550-164cc6292ab8 none luks,initramfs

nvim /etc/default/grub
GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 cryptdevice=UUID=4f81b0a5-8aac-4f80-8060-469e1457eafc:cryptroot root=/dev/mapper/cryptroot nvidia-drm.modeset=1 rootfstype=btrfs rootflags=rw root_trim=yes"
GRUB_CMDLINE_LINUX=""

nvim /etc/crypttab
498c9752-3642-4121-b37f-b9a9b8204988

pacman -S kernel-install-for-dracut

reinstall-kernels

sudo grub-install --target=x86_64-efi --efi-directory=/boot && sudo grub-install --target=x86_64-efi --efi-directory=/boot --removable && sudo grub-mkconfig -o /boot/grub/grub.cfg

** Systemd Setup
systemctl enable NetworkManager fstrim.timer acpid sysstat reflector reflector.timer auditd chronyd

** Secure Boot Setup

-- WARNING -- This system is for the use of authorized users only. Individuals
using this computer system without authority or in excess of their authority
are subject to having all their activities on this system monitored and
recorded by system personnel. Anyone using this system expressly consents to
such monitoring and is advised that if such monitoring reveals possible
evidence of criminal activity system personal may provide the evidence of such
monitoring to law enforcement officials.

## build toolchain
linux-api-headers- >glibc >binutils >gcc >glibc >binutils >gcc

#chroot into endeavoros
cryptsetup open --perf-no_read_workqueue --perf-no_write_workqueue --persistent /dev/nvme1n1p2 cryptroot && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@ /dev/mapper/cryptroot /mnt/ && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@home /dev/mapper/cryptroot /mnt/home && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@opt /dev/mapper/cryptroot /mnt/opt && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@tmp /dev/mapper/cryptroot /mnt/tmp && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@var /dev/mapper/cryptroot /mnt/var && mount -o nmoatime,compress=zstd,space_cache=v2,discard=async,subvol=@log /dev/mapper/cryptroot /mnt/var/log && mount -o nmoatime,compress=zstd,space_cache=v2,discard=async,subvol=@audit /dev/mapper/cryptroot /mnt/var/log/audit && mount -o noatime,compress=zstd,space_cache=v2,discard=async,subvol=@snapshots /dev/mapper/cryptroot /mnt/.snapshots
