#!/bin/bash
echo "Settig up git"
sleep 3
sudo apt install -y gnome-keyring libsecret-1-0 libsecret-1-dev
sudo make --directory=/usr/share/doc/git/contrib/credential/libsecret
git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret
git config --global user.name "zielOS"
git config --global user.email "ahsanur041@gmail.com"
