#!/bin/bash
echo "Setting up Dotfiles"
sudo rm -R ~/.config/
cd && mkdir $HOME/.config
ln -sv $HOME/.dots/gentoo_setup $HOME/
ln -sv $HOME/.dots/org $HOME/
ln -sv $HOME/.dots/.config/hypr $HOME/.config/
ln -sv $HOME/.dots/.config/bat $HOME/.config/
ln -sv $HOME/.dots/.config/Thunar $HOME/.config/
ln -sv $HOME/.dots/.config/rofi $HOME/.config/
ln -sv $HOME/.dots/.config/alacritty $HOME/.config/
ln -sv $HOME/.dots/.config/kitty $HOME/.config/
ln -sv $HOME/.dots/.config/foot $HOME/.config/
ln -sv $HOME/.dots/.config/btop $HOME/.config/
ln -sv $HOME/.dots/.config/Kvantum $HOME/.config/
ln -sv $HOME/.dots/.config/lazygit $HOME/.config/
ln -sv $HOME/.dots/.config/nvim $HOME/.config/
ln -sv $HOME/.dots/.config/qalculate $HOME/.config/
ln -sv $HOME/.dots/.config/qt5ct $HOME/.config/
ln -sv $HOME/.dots/.config/qt6ct $HOME/.config/
ln -sv $HOME/.dots/.config/yazi $HOME/.config/
ln -sv $HOME/.dots/.config/wallpapers $HOME/.config/
ln -sv $HOME/.dots/.config/zathura $HOME/.config/
ln -sv $HOME/.dots/.config/chromium-flags.conf $HOME/.config/
ln -sv $HOME/.dots/.local/bin/hypr $HOME/.local/bin/

# git setup

xdg-user-dirs-update
#cd && cp -R ~/.dots/.config/nix/ ~/.config/
#cd && cp -R ~/.dots/.config/home-manager/ ~/.config/

mkdir ~/.config/zellij
zellij setup --dump-config >~/.config/zellij/config.kdl
