#!/bin/bash

# Set Up Systemd
sudo systemctl set-default graphical.target
systemctl --user enable --now wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service
sudo systemctl disable greetd

systemctl --user enable --now hypridle.service hyprpaper.service
