#!/bin/bash
sudo apt install -y curl 
cd && git clone https://github.com/jandamm/zgenom.git "${HOME}/.zgenom"
ln -sv $HOME/.dots/.config/zsh $HOME/.config/
#ln -sv $HOME/.dots/.config/starship.toml $HOME/.config/
ln -sv $HOME/.dots/.zshrc $HOME/
chsh -s $(which zsh)

