#!/bin/bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install bottom
brew install yazi
brew install zellij
brew install atuin
brew install lazygit

