#!/bin/bash
sudo apt install -y curl 
sudo rm -rf ~/.bash*
ln -sv $HOME/.dots/.config/atuin $HOME/.config/
ln -sv $HOME/.dots/.config/bash $HOME/.config/
ln -sv $HOME/.dots/.bashrc $HOME/

echo "Installing blesh"
sleep 2
cd && git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git
cd ble.sh
make install
cd && sudo rm -rf ble*
cd && source .bashrc

