#!/bin/bash

echo "@npm"
sleep 5
cd && mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
npm install -g bun sass

echo "@dots"
sleep 5
sudo rm -R $HOME/.local
sudo rm -R $HOME/.config/
cd && mkdir $HOME/.config
mkdir -p $HOME/.local/bin
ln -sv $HOME/.dots/.config/ags/ $HOME/.config/
ln -sv $HOME/.dots/.config/alacritty $HOME/.config/
ln -sv $HOME/.dots/.config/kitty $HOME/.config/
ln -sv $HOME/.dots/.config/gtk-3.0 $HOME/.config/
ln -sv $HOME/.dots/.config/gtk-4.0 $HOME/.config/
ln -sv $HOME/.dots/.config/hypr $HOME/.config/
ln -sv $HOME/.dots/.config/Kvantum $HOME/.config/
ln -sv $HOME/.dots/.config/lazygit $HOME/.config/
ln -sv $HOME/.dots/.config/lsd $HOME/.config/
ln -sv $HOME/.dots/.config/Thunar $HOME/.config/
ln -sv $HOME/.dots/.config/qt5ct $HOME/.config/
ln -sv $HOME/.dots/.config/qt6ct $HOME/.config/
ln -sv $HOME/.dots/.config/wallpapers $HOME/.config/
ln -sv $HOME/.dots/.local/bin/hypr $HOME/.local/bin
ln -sv $HOME/.dots/.config/zathura $HOME/.config/
ln -sv $HOME/.dots/.config/zsh $HOME/.config/
ln -sv $HOME/.dots/.config/starship.toml $HOME/.config/
ln -sv $HOME/.dots/.gtkrc-2.0 $HOME/
ln -sv $HOME/.dots/.themes $HOME/
ln -sv $HOME/.dots/.fonts $HOME/
ln -sv $HOME/.dots/org $HOME/

cd && cd ~/.config/ags
bash install_fonts.sh
cd

echo "@systemd"
sleep 5
sudo systemctl set-default graphical.target
systemctl --user enable --now wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service

echo "@nvim-init"
sleep 5
ln -s $HOME/.dots/.config/nvim $HOME/.config/

echo "@zsh"
sleep 5
cd && curl -fsSL https://fnm.vercel.app/install | sh
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
rm -R .zshrc
ln -s $HOME/.dots/.zshrc ~/
chsh -s $(which zsh)

echo "@git"
sleep 5
sudo cp -R ~/.dots/variables.sh /etc/profile.d/
git config --global user.name "zielOS"
git config --global user.email "ahsanur041@gmail.com"
git config --global credential.helper /usr/libexec/git/git-credential-libsecret

echo "@pipx"
pipx install hyprshade pyprland
