#!/bin/sh
echo "@asus"
sudo zypper ar --priority 50 --refresh https://download.opensuse.org/repositories/home:/luke_nukem:/asus/openSUSE_Tumbleweed/ asus-linux
sudo transactional-update -c pkg install asusctl supergfxctl asusctl-rog-gui power-profiles-daemon
sudo systemctl enable --now power-profiles-daemon.service supergfxd

echo "aylurs-gtk-shell"
sudo zypper addrepo https://download.opensuse.org/repositories/home:Rethil/openSUSE_Tumbleweed/home:Rethil.repo
sudo zypper refresh
sudo transactional-update -c pkg install aylurs-gtk-shell

echo "swaylock-effects"
sudo zypper addrepo https://download.opensuse.org/repositories/home:zilti:hyprland/openSUSE_Tumbleweed/home:zilti:hyprland.repo
sudo zypper refresh
sudo transactional-update -c pkg install swaylock-effects
