#!/bin/bash
flatpak install flathub io.github.zen_browser.zen
flatpak install flathub com.ticktick.TickTick
flatpak install flathub com.bitwarden.desktop
flatpak install flathub org.onlyoffice.desktopeditors
flatpak install flathub io.github.celluloid_player.Celluloid
flatpak install flathub com.github.tchx84.Flatseal
flatpak install flathub com.spotify.Client
flatpak install flathub com.notesnook.Notesnook
flatpak install flathub com.google.Chrome
flatpak install flathub com.github.xournalpp.xournalpp
flatpak install flathub io.github.b43NnUNF4vidFYFhpqaLWy2ANawtRbMtUXZY9Pf.jumpdf
