[pyprland]
plugins = [ "scratchpads" ]

[scratchpads.term]
command = "alacritty --class alacritty-dropterm"
animation = "fromTop"
unfocus = "hide"

[scratchpads.ranger]
command = "kitty --class explorer -e ranger"
animation = "fromBottom"
unfocus = "hide"
