#!/bin/bash
cd && git clone https://github.com/jiixyj/epoll-shim.git
cd epoll-shim && mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build .
cmake --build . --target install
cd && sudo rm -rf epoll-shim
