#!/bin/bash
echo "Installing hyprpaper"
sudo apt install -y libmagic-dev libturbojpeg0-dev
cd && git clone https://github.com/hyprwm/hyprpaper.git
cd hyprpaper
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprpaper -j$(nproc 2>/dev/null || getconf NPROCESSORS_CONF)
sudo cmake --install ./build
cd && sudo rm -rf hyprpaper
