#!/bin/bash
echo "Initial Setup"
cd
sudo apt install -y zstd curl linux-image-$(uname -r) linux-headers-$(uname -r) linux-tools-$(uname -r) gcc make acpid dkms libglvnd-core-dev libglvnd0 libc-dev apt-listchanges apt-show-versions debsums linux-firmware btrfs-progs network-manager vim console-setup pkg-config plymouth plymouth-themes efibootmgr wget curl needrestart apt-transport-https apt-rollback texinfo

sudo update-grub2

echo "Finished Installing Initial Packages"

#sudo reboot
