#!/bin/bash

sh <(curl -L https://nixos.org/nix/install) --daemon
sudo rm -rf /etc/nix
sudo ln -sv $HOME/.dots/.config/nix /etc/
nix run home-manager/master -- init --switch --extra-experimental-features nix-command --extra-experimental-features flakes

