#!/bin/bash

sh <(curl -L https://nixos.org/nix/install) --daemon
nix run home-manager/master -- init --switch --extra-experimental-features nix-command --extra-experimental-features flakes
ln -sv $HOME/.dots/.config/nix $HOME/.config/
