#!/bin/bash
echo "Installing Graphics Drivers"
sleep 2
#ubuntu approach
sudo apt install -y nvidia-dkms-560 --install-recommends
sudo apt install -y nvidia-driver-560 xserver-xorg-video-nvidia-560 --install-recommends
sudo apt install -y nvidia-vaapi-driver vdpau-driver-all xserver-xorg-video-amdgpu mesa-utils-bin mesa-vulkan-drivers libnvidia-gl-560 vulkan-tools vulkan-utility-libraries-dev vulkan-validationlayers nvidia-firmware-560-560.35.03 --install-recommends

sudo systemctl disable --now nvidia-persistenced
echo "Finished Installing Graphics Drivers"
