#!/bin/bash
echo "Installing From Source"
bash $HOME/.dots/ubuntu-scripts/source_builds/Asuslinux && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Emacs && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprutils && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprlang && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprcursor && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprwayland-scanner && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprgraphics && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprpaper && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprpicker && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hypridle && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprlock && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Aquamarine && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Xdg-desktop-portal-hyprland && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprland && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprland-contrib && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Hyprsunset && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Neovim && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Nwg-hello && cd
bash $HOME/.dots/ubuntu-scripts/source_builds/Rofi && cd
echo "Done building packages from source"
