#!/bin/bash
echo "Initial Setup"
cd
sudo apt install -y zstd curl linux-headers-amd64 gcc make acpid dkms libglvnd-core-dev libglvnd0 libc-dev apt-listchanges needrestart apt-show-versions debsums firmware-linux btrfs-progs network-manager vim console-setup pkg-config plymouth efibootmgr wget curl apt-listbugs

sudo update-grub2

#sudo reboot
