#!/bin/bash
echo "Initial Setup"
cd
sudo apt install zstd curl linux-headers-amd64 gcc make acpid dkms libglvnd-core-dev libglvnd0 libc-dev apt-listbugs apt-listchanges needrestart apt-show-versions debsums flatpak firmware-linux btrfs-progs network-manager vim console-setup pkg-config plymouth efibootmgr wget curl

flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

sudo reboot
