#!/bin/bash
## debian method
# sudo apt purge --autoremove nvidia-driver-full nvidia-kernel-dkms nvidia-vaapi-driver xserver-xorg-video-amdgpu mesa-utils vulkan-validationlayers vulkan-tools nvidia-vulkan-common mesa-vulkan-drivers firmware-nvidia-graphics --install-recommends
# sudo systemctl disable nvidia-persistenced

## cuda method
cd && wget https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt update -y
sudo apt install -y nvidia-open 
sudo apt install -y nvidia-vaapi-driver nvidia-vdpau-driver xserver-xorg-video-amdgpu mesa-utils vulkan-validationlayers vulkan-tools nvidia-vulkan-common mesa-vulkan-drivers firmware-nvidia-graphics 
sudo systemctl disable nvidia-persistenced
cd && sudo rm -R cuda-keyring_1.1-1_all.deb
#sudo reboot
