#!/bin/bash
flatpak install flathub io.github.zen_browser.zen -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub org.zotero.Zotero -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.notesnook.Notesnook -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub org.squidowl.halloy -y
flatpak install flathub com.dropbox.Client -y
flatpak install flathub md.obsidian.Obsidian -y
