#!/bin/bash
## Custom Scripts
sudo ln -sv $HOME/.dots/bin/hyprterm /usr/local/bin/hyprterm
sudo ln -sv $HOME/.dots/bin/hyprmenu /usr/local/bin/hyprmenu
sudo ln -sv $HOME/.dots/bin/hyprtheme /usr/local/bin/hyprtheme
sudo ln -sv $HOME/.dots/bin/reload_ags /usr/local/bin/reload_ags

## Go Packages
sudo ln -sv $HOME/go/bin/lazygit /usr/local/bin/lazygit

## Cargo Packages
sudo ln -sv $HOME/.cargo/bin/yazi /usr/local/bin/yazi
sudo ln -sv $HOME/.cargo/bin/ya /usr/local/bin/ya
sudo ln -sv $HOME/.cargo/bin/zellij /usr/local/bin/zellij
sudo ln -sv $HOME/.cargo/bin/hyprnome /usr/local/bin/hyprnome
sudo ln -sv $HOME/.cargo/bin/matugen /usr/local/bin/matugen
sudo ln -sv $HOME/.cargo/bin/btm /usr/local/bin/btm

## Bun packages -- see if removing these packages fixes ags install problems
sudo ln -sv $HOME/.bun/bin/sass /usr/local/bin/sass
sudo ln -sv $HOME/.bun/bin/tsc /usr/local/bin/tsc
sudo ln -sv $HOME/.bun/bin/tsserver /usr/local/bin/tsserver
