[manager]
layout = [1, 2, 4]
linemode = "none"
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true

[preview]
cache_dir = ""
image_filter = "lanczos3"
image_quality = 90
max_height = 900
max_width = 600
tab_size = 1
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1

[tasks]
bizarre_retry = 5
macro_workers = 10
micro_workers = 5

[flavor]
use = "catppuccin-macchiato"
# For upcoming Yazi 0.4 (nightly version):
dark = "catppuccin-macchiato"

[[plugin.prepend_previewers]]
mime = "application/{,g}zip"
run  = "lsar"

[[plugin.prepend_previewers]]
mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}"
run  = "lsar"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
