#!/bin/bash
echo "Installing aquamarine"
sleep 3
sudo apt install -y libseat-dev libinput-dev libdisplay-info-dev
cd && git clone https://github.com/hyprwm/aquamarine.git 
cd aquamarine && git checkout v0.4.5
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
sudo cmake --install ./build
cd && sudo rm -rf aquamarine 
