#!/bin/bash
# Export the sha256sum for verification.
export DOCKFMT_SHA256="f6bc025739cf4f56287e879c75c11cc73ebafdf93a57c9bcd8805d1ab82434a0"

# Download and check the sha256sum.
curl -fSL "https://github.com/jessfraz/dockfmt/releases/download/v0.3.3/dockfmt-linux-amd64" -o "/usr/local/bin/dockfmt" \
	&& echo "${DOCKFMT_SHA256}  /usr/local/bin/dockfmt" | sha256sum -c - \
	&& chmod a+x "/usr/local/bin/dockfmt"

echo "dockfmt installed!"

# Run it!
dockfmt -h
