#!/bin/bash
echo "Installing Emacs"
sleep 2
sudo apt install -y libgccjit-14-dev libmagick++-dev
cd && wget https://gnu.mirror.constant.com/emacs/emacs-29.4.tar.xz
tar -xvf emacs-29.4.tar.xz && cd emacs-29.4 && ./autogen.sh
./configure --with-pgtk --with-native-compilation --with-mailutils --with-imagemagick --with-tree-sitter --with-threads 
make -j12
sudo make uninstall && cd && sudo rm -rf emacs-*
