#!/bin/sh
echo "Installing hyprlang"
sleep 3
cd && git clone https://github.com/hyprwm/hyprlang.git
cd hyprlang && git checkout v0.5.3
sleep 3
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprlang -j$(nproc 2>/dev/null || getconf NPROCESSORS_CONF)
sudo cmake --install ./build
cd && sudo rm -rf hyprlang
