#!/bin/bash
echo "Installing Neovim"
sleep 3
sudo apt-get install python3-pynvim ripgrep tree-sitter-cli fd-find ninja-build gettext cmake unzip curl build-essential
cd && git clone https://github.com/neovim/neovim
cd neovim && git checkout stable
sleep 3
make CMAKE_BUILD_TYPE=RelWithDebInfo -j22
sudo make install && cd && sudo rm -rf neovim
