#!/bin/bash

directory=/notexist

if [ -d $directory ]; then
  echo "The directory $directory exists."
  echo $?
else
  echo "The directory $directory does not exist."
  echo $?
fi

echo "The exit code for this script run is $?"
