#!/bin/bash

mynum=300

if [ $mynum -eq 200 ]; then
  echo "The condition is true."
else
  echo "The condition is false"
fi

if [ $mynum -ne 200 ]; then
  echo "The condition is true."
else
  echo "The condition is false"
fi

if [ $mynum -lt 200 ]; then
  echo "The condition is true."
else
  echo "The condition is false"
fi

if [ -f ~/myfile ]; then
  echo "The file exists"
else
  echo "The file does not exist"
fi

command=htop

if command -v $command; then #command checks if a command is available
  echo "$command is available"
else
  echo "$command is not available, installing it,,,,"
  sudo pacman -Sy $command
fi

$command
