#!/bin/bash

yay -S --noconfirm \
  acpid arch-audit amd-ucode \
  bat brave-bin btrfs-progs boost boxbuddy btop btrfs-progs bleachbit bitwarden brightnessctl \
  chrony curl cmake chkrootkit cups cliphist \
  dosfstools dbus-python devtools deluge direnv dropbox downgrade pacman-contrib \
  emacs-wayland eza \
  fd flatpak fzf fdupes fastfetch fnm foot fwupd freeoffice \
  grim greetd gnome-keyring gjs gtk3 gtk4 gnome-bluetooth-3.0 gobject-introspection gtk-layer-shell gtk4-layer-shell grub grub-btrfs grub-customizer gst-plugin-pipewire gst-plugins-bad gst-plugins-ugly gst-plugins-good gvfs-goa \
  haveged hyprlang-git hyprcursor-git hyprwayland-scanner-git hypridle-git hyprlock-git hyprnome hyprdim hyprpaper-git hyprpicker-git hyprland-git hyprsunset-git \
  jq jitterentropy-rngd \
  kvantum kvantum-qt5 kvantum-theme-catppuccin-git \
  logseq-desktop-bin lynis libdbusmenu-gtk3 libsoup3 logrotate libva \
  mesa mate-polkit mpv meson \
  networkmanager notesnook-bin nwg-hello nwg-look nwg-drawer nodejs npm nodejs-neovim \
  org.freedesktop.secrets onlyoffice-bin obsidian \
  pamac-all papirus-icon-theme python-pip python-pipx python-pynvim pipewire pipewire-alsa pipewire-pulse pavucontrol pyprland python-pam plocate \
  qalculate-gtk qt5-wayland qt6-wayland qt5ct qt6ct \
  rng-tools rbenv rofi-wayland rofi-rbw rust ripgrep \
  swappy sysstat slurp swww sassc snapper snap-pac snap-pac-grub spotify-launcher starship sof-firmware smartmontools \
  tealdeer thunar thunar-volman thunar-media-tags-plugin thunar-archive-plugin tumbler tree-sitter-cli ttf-jetbrains-mono-nerd ttf-jetbrains-mono ttf-ubuntu-font-family typescript \
  unzip unrar upower \
  vulkan-tools vulkan-headers vulkan-validation-layers \
  wl-clipboard wf-recorder wget wireplumber \
  xorg-xwayland xournalpp xarchiver xdg-user-dirs xdg-desktop-portal-hyprland xz xf86-video-amdgpu \
  unzip \
  yazi \
  zathura zathura-pdf-poppler zen-browser-avx2-bin zoxide zotero-bin zip

