#!/bin/bash
yay -S aardvark-dns cockit cockpit-packagekit cockit-podman distrobox lxd netavark podman podman-docker
sudo systemctl enable --now docker.service
sudo systemctl enable --now lxd.service
sudo systemctl enable --now cockpit.socket
