#!/bin/bash
echo "Installing gtk theme"
sudo pacman -S gnome-themes-extra gtk-engine-murrine sassc catppuccin-gtk-theme-macchiato papirus-icon-theme papirus-folders-catppuccin-git bibata-cursor-theme 

