#!/bin/bash
sudo systemctl set-default graphical.target
sudo systemctl enable grub-btrfsd
systemctl --user enable wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service hypridle.service
sudo systemctl enable --now jitterentropy sysstat  haveged NetworkManager
sudo systemctl disable greetd
 
