#!/bin/bash
yay -S asusctl power-profiles-daemon supergfxctl switcheroo-control rog-control-center 
sudo systemctl enable --now power-profiles-daemon.service
sudo systemctl enable --now supergfxd
sudo systemctl enable --now switcheroo-control
