#!/bin/bash
sudo pacman -S typescript npm meson gjs gtk3 gtk-layer-shell gnome-bluetooth-3.0 upower networkmanager gobject-introspection libdbusmenu-gtk3 libsoup3
sudo pacman -S pipewire libgtop bluez bluez-utils btop networkmanager dart-sass wl-clipboard brightnessctl swww python gnome-bluetooth-3.0 pacman-contrib power-profiles-daemon gvfs
yay -S grimblast-git gpu-screen-recorder matugen-bin python-gpustat 
cd && git clone --recursive https://github.com/Aylur/ags.git
cd ags && git checkout v1.8.2
npm install
meson setup build
sudo meson install -C build
cd && ags

