#!/bin/bash

sh <(curl -L https://nixos.org/nix/install) --daemon
# nix run home-manager/master -- init --switch --extra-experimental-features nix-command --extra-experimental-features flakes
sudo rm -rf /etc/nix
sudo mkdir /etc/nix
sudo cp -R $HOME/.dots/arch-scripts/preconfig-files/nix.conf /etc/nix/
yay -S zsh-nix-shell nix-zsh-completions
